---
title: "Support supervision dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: row
    vertical_layout: fill
    social: ["menu"]
    theme:
      version: 4
      bootswatch: minty

---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(palmerpenguins)
library(plotly)
library(DT)
library(fontawesome)
data("penguins")
```

Plots{data-navmenu="pages"}
======================================================================

sidebar {.sidebar}
-----------------------------------------------------------------------

### Penguin Stats
The number of penguins is data is `r nrow (penguins)`

Row
------------------------------------------------------------------
### Number of penguins
```{r}

valueBox(nrow(penguins), icon = "fa-linux")
```


Column {.tabset}
-----------------------------------------------------------------------

### scatter plot

```{r}
a= penguins %>% ggplot( aes(x = bill_length_mm, y = bill_depth_mm, color = species))+
  geom_point()

ggplotly(a)
```


### Chart B

```{r}
penguins %>% ggplot(aes(
  x = body_mass_g, y = sex, fill = sex
))+
  geom_boxplot()

```

### Chart C

```{r}
penguins %>%  ggplot( aes( x =flipper_length_mm, fill = species ))+
  geom_histogram()+
  facet_wrap(~species)

```

Data {data-navmenu="pages"}
=========================================================================
```{r}
penguins %>% datatable(extensions = "Buttons",
                       options = list(dom = "Blfrtip",
                                      buttons = c("Copy", "Excel", "PDF","CSV")))
  
```


